-- return {
-- 	"yetone/avante.nvim",
-- 	enabled = false,
-- 	event = "VeryLazy",
-- 	lazy = false,
-- 	version = false,
-- 	opts = {
-- 		auto_suggestions_provider = "claude",
-- 		suggestion = {
-- 			debounce = 10,
-- 		},
-- 		behaviour = {
-- 			auto_suggestions = true,
-- 		},
-- 		windows = {
-- 			---@type "right" | "left" | "top" | "bottom"
-- 			position = "right", -- the position of the sidebar
-- 			wrap = true, -- similar to vim.o.wrap
-- 			width = 30, -- default % based on available width
-- 			sidebar_header = {
-- 				enabled = true, -- true, false to enable/disable the header
-- 				align = "center", -- left, center, right for title
-- 				rounded = true,
-- 			},
-- 			input = {
-- 				prefix = "> ",
-- 				height = 8, -- Height of the input window in vertical layout
-- 			},
-- 			edit = {
-- 				border = "rounded",
-- 				start_insert = true, -- Start insert mode when opening the edit window
-- 			},
-- 			ask = {
-- 				floating = false, -- Open the 'AvanteAsk' prompt in a floating window
-- 				start_insert = true, -- Start insert mode when opening the ask window
-- 				border = "rounded",
-- 				---@type "ours" | "theirs"
-- 				focus_on_apply = "ours", -- which diff to focus after applying
-- 			},
-- 		},
-- 	},
--
-- 	build = "make",
-- 	dependencies = {
-- 		"stevearc/dressing.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		"hrsh7th/nvim-cmp",
-- 		{
-- 			-- support for image pasting
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				-- recommended settings
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = {
-- 						insert_mode = true,
-- 					},
-- 				},
-- 			},
-- 		},
-- 		{
-- 			-- Make sure to set this up properly if you have lazy=true
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = {
-- 				file_types = { "markdown", "Avante" },
-- 			},
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- }
